
# Site settings
title: Francisco documentation
email: 1074896@pdsb.net
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://1074896-glitch.github.io/" # the base hostname & protocol for your site

markdown: kramdown
# toc_levels: 1……2

# paginate: 10
# paginate_path: ":num"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - blog pull and debug.bat
